version: '3.9'

services:

  ### PHP ##############################################
  php:
    image: ladit/php
    # build:
    #   context: ./php
    #   args:
    #     - http_proxy
    #     - https_proxy
    #     - no_proxy
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/fpm.conf:/usr/local/etc/php-fpm.d/zz-fpm.conf
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/web.ini:/usr/local/etc/php/conf.d/web.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${DATA_BASE_HOST}/xdebug:/var/local/xdebug
      - ${CODE_BASE_HOST}:${CODE_BASE_CONTAINER}
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  ### NGINX Server #########################################
  nginx:
    image: ladit/nginx
    # build:
    #   context: ./nginx
    #   args:
    #     - http_proxy
    #     - https_proxy
    #     - no_proxy
    volumes:
      - ./nginx/40-crond.sh:/docker-entrypoint.d/40-crond.sh
      - ./nginx/logrotate:/etc/logrotate.d/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ${CODE_BASE_HOST}:${CODE_BASE_CONTAINER}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php

  ### MySQL ################################################
  # mysql:
  #   build:
  #     context: ./mysql
  #     args:
  #       - MYSQL_VERSION=${MYSQL_VERSION}
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ${DATA_BASE_HOST}/mysql:/var/lib/mysql
  #     - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - "${MYSQL_PORT}:3306"
